version: '3'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  

  authentication-service:
    image: kathyleesh/authentication-service:latest
    ports:
      - "8080:8080"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      JAVA_OPTS: "-Xms256m -Xmx512m -XX:+UseG1GC"
    depends_on:
      - redis

  enjoy-service:
    image: kathyleesh/enjoy-service:latest
    ports:
      - "8081:8081"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      JAVA_OPTS: "-Xms256m -Xmx512m -XX:+UseG1GC"

  safe-service:
    image: kathyleesh/safe-service:latest
    ports:
      - "8082:8082"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      JAVA_OPTS: "-Xms256m -Xmx512m -XX:+UseG1GC"

  recommendation-service:
    image: kathyleesh/recommendation-service:latest
    ports:
      - "8003:8003"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      MONGO_URL: ${MONGO_URL}

  chatting-service:
    image: kathyleesh/chatting-service:latest
    ports:
      - "8083:8083"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      JAVA_OPTS: "-Xms256m -Xmx512m -XX:+UseG1GC"
    depends_on:
      - zookeeper
      - kafka
      - kafka-ui

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"


networks:
  default:
    external:
      name: nubio
